language: node_js
cache:
  directories: node_modules
node_js:
  - '6'
script:
  - npm run lint
  - npm test

notifications:
  slack:
    secure: MGFoHX9owpwi53mb3ovldHODwX4TWeTo1D3mSYX6xexkmfirhC6Ky1FX9Q6pt0pVovQ/i7HZoYa/kzRMGTFZOFd0lpvnLL1QYJwZIYwrfCm2Rnzk7kzgAOqztzFI2rAnGDQzMpAuda9Pd221b/CjW05YBniauhElXgu1RrujAwwZ6FOWvnqDCDEspGp7Xdc9z0JfKJ9+TSA/jezcs1qOmUV/Sul7dOWx075kZMkUCXH5n9av3WgCpR7nWk1ggD+sFlze2CJ7/HrRq0tgTqwDQgQj40Eu2fS1jcNFqTV5fURGN6IfYfAs96LBEmiisen9G7PCecdFD5j6bj29i9pRH0KecUTuRXJE0jWd0Uf5F3SE/3wt8geANA/Zrz+vhmZ45XkzaXQykCqWnwuQ7pG0vW0SszQh5tVKBtR/5NA5CggIoxt/HQex4VUIFsUbkDpY5lyLzhVEC2P0bQIj3fvOamCRFUgTy742yij9A7eE3HHAKin7H4L7kVa0Zkfh4iVACZN5x4S2hgd9DwxQo7Nyi0K2iVU9MHzEda8upK9Zwd+oErm39HLsEqiWb9UoKtx89RrEXvzT33iEOCB5SY7s2D6RhXS+fARkRF9dSuu6PEaLu0FSr3DB5Wt0qKlGHepGj/EeGXiigI0teZVcY0HRUpaZVOV/SauZn9wZedlxlqc=

before_deploy: npm run dist
deploy:
  - provider: gcs
    bucket: floq-test
    local-dir: dist
    upload-dir: balance
    cache_control: "max-age=0"
    acl: public-read
    access_key_id: GOOGUTBTHMJF3QCW6R7F
    secret_access_key:
      secure: E8fXIgyV/hkAosVHP4hNJHE+ButxDkH7jy94wkfmpWrm0onD/8OrtedwD4PiBMNy1NGz/THs93x5tw+pot1kg87oaod39BO2u9TaK7UMjL/kw6yb1mBKTmAh3Zq6v79iHqHfFdwRLxpDQOmVmpW7wrJFpjTdUWftEefOaHgWT95pFIEbkYzplGf+IPNM3MBYYz0vTrhgLCCE9Ig6diE3I5+lYbdXhFc+8DPpcql2zhbFAk+shdm152XkEgHY3j1Run7YuzXScoxdFWedE2M4+vIZ7GJ/SpEqfyNUhAO3DZuTPbHSC7IOFjQWz9OhoS0I1LIJ56nYeIX47qPp59pGb7zf5wNKTVk7gN7k5X4hY3AGtlbppiJPFEcwL7p5EL15v9We65LuUgFqItLumt+tueVrSUIshexzGDMdzEh4GG6chWjD7iAHFovlu3xRafkUuVdN9YkW35P4zZSsSMv8mao8H2io1qeS+s6So+uZ/TrFmu432GKEizyu8BfZ42fxFMYnYyJs0sQMBWtkhxTYK203By5wMSNyvTrs79P1kRTUBhvHrKFtIKFILrwFrUvfsOCV3W3+VebyzWPT3c9J2IIFr0Uw3lmYppgSagaw5hAkiR4kTLSOyGmUFLHiN7R91+m38p6q9NhH+NOb3Qi1MF2i8W8XIoynTDIMDiG0A3k=
    skip_cleanup: true
    on:
      repo: blankoslo/floq-balance
      branch: develop
  - provider: gcs
    bucket: floq
    local-dir: dist
    upload-dir: balance
    cache_control: "max-age=3600"
    acl: public-read
    access_key_id: GOOGUTBTHMJF3QCW6R7F
    secret_access_key:
      secure: E8fXIgyV/hkAosVHP4hNJHE+ButxDkH7jy94wkfmpWrm0onD/8OrtedwD4PiBMNy1NGz/THs93x5tw+pot1kg87oaod39BO2u9TaK7UMjL/kw6yb1mBKTmAh3Zq6v79iHqHfFdwRLxpDQOmVmpW7wrJFpjTdUWftEefOaHgWT95pFIEbkYzplGf+IPNM3MBYYz0vTrhgLCCE9Ig6diE3I5+lYbdXhFc+8DPpcql2zhbFAk+shdm152XkEgHY3j1Run7YuzXScoxdFWedE2M4+vIZ7GJ/SpEqfyNUhAO3DZuTPbHSC7IOFjQWz9OhoS0I1LIJ56nYeIX47qPp59pGb7zf5wNKTVk7gN7k5X4hY3AGtlbppiJPFEcwL7p5EL15v9We65LuUgFqItLumt+tueVrSUIshexzGDMdzEh4GG6chWjD7iAHFovlu3xRafkUuVdN9YkW35P4zZSsSMv8mao8H2io1qeS+s6So+uZ/TrFmu432GKEizyu8BfZ42fxFMYnYyJs0sQMBWtkhxTYK203By5wMSNyvTrs79P1kRTUBhvHrKFtIKFILrwFrUvfsOCV3W3+VebyzWPT3c9J2IIFr0Uw3lmYppgSagaw5hAkiR4kTLSOyGmUFLHiN7R91+m38p6q9NhH+NOb3Qi1MF2i8W8XIoynTDIMDiG0A3k=
    skip_cleanup: true
    on:
      repo: blankoslo/floq-balance
      branch: master
