language: node_js
cache:
  directories: node_modules
node_js:
  - '6'
script:
  - npm run lint
  - npm test

notifications:
  slack:
    secure: MGFoHX9owpwi53mb3ovldHODwX4TWeTo1D3mSYX6xexkmfirhC6Ky1FX9Q6pt0pVovQ/i7HZoYa/kzRMGTFZOFd0lpvnLL1QYJwZIYwrfCm2Rnzk7kzgAOqztzFI2rAnGDQzMpAuda9Pd221b/CjW05YBniauhElXgu1RrujAwwZ6FOWvnqDCDEspGp7Xdc9z0JfKJ9+TSA/jezcs1qOmUV/Sul7dOWx075kZMkUCXH5n9av3WgCpR7nWk1ggD+sFlze2CJ7/HrRq0tgTqwDQgQj40Eu2fS1jcNFqTV5fURGN6IfYfAs96LBEmiisen9G7PCecdFD5j6bj29i9pRH0KecUTuRXJE0jWd0Uf5F3SE/3wt8geANA/Zrz+vhmZ45XkzaXQykCqWnwuQ7pG0vW0SszQh5tVKBtR/5NA5CggIoxt/HQex4VUIFsUbkDpY5lyLzhVEC2P0bQIj3fvOamCRFUgTy742yij9A7eE3HHAKin7H4L7kVa0Zkfh4iVACZN5x4S2hgd9DwxQo7Nyi0K2iVU9MHzEda8upK9Zwd+oErm39HLsEqiWb9UoKtx89RrEXvzT33iEOCB5SY7s2D6RhXS+fARkRF9dSuu6PEaLu0FSr3DB5Wt0qKlGHepGj/EeGXiigI0teZVcY0HRUpaZVOV/SauZn9wZedlxlqc=

before_deploy: npm run dist
deploy:
  - provider: gcs
    bucket: floq-test
    local-dir: dist
    upload-dir: balance
    cache_control: "max-age=0"
    acl: public-read
    access_key_id: GOOGUTBTHMJF3QCW6R7F
    secret_access_key:
      secure: I/9aJ7u/BrImFT7GuBw+1zvj3oG/a8qKhJ14HnIvFsruglZQHl4sT+GzFRmMk+ZV43NW8Nfm4rL/uUt+cEWG4FRKebbNCH4ftueZi9UgDiotHSdOb5DVwBHgmzvGv7lt5mtGpceu7kTxW24hYXxu+q9o+pAaAjVonDMGLSk4P1wORHPEcdAZRlfrNcS55RZNgErDIteB5GbGo2f7ivKnQ0YvayLtupyi73+Ka68BBqnTDu1Y7akkdYq4dp6HD857aXhaZa+Dcsz6JkN2sSAGk0fAJ9VyPQi/pQWFA5D1i1fDillnA1beelXCWrfckPSzrb/nsJoK+srx9jvu7bxLu0NBL/ZwewrTSbr7nE9lmvG6qONxD7U/nBaC2iwSVJIXkQ392Ff2NiQ09htNCxr1w5eqT5s7d/4vlPJ/Yzkm+AWtQJfl2yzaK2k3Ev5gyFt3pa+EgB/wGiJW0u/8n5S0c5rcEROaKluryvOAcRQvmLXfK0FBljl3jf11gW+rO7DG4Dj2YeS67ZYzm+Gcmq3IK6k6gIC4KXuW/oZSGUM+wE7NndfwaYfNcanM1QS/KMuZbW3OTwS/R7wkBhWFWcAURyhKj+4rjvWawzFNn//8Kb0mQjFsnwwt1lBzNbeAH1QIaaFtDa0R4S7nUPHleRW9dkGV5iRsFWvL7Up4m6KIwyo=
    skip_cleanup: true
    on:
      repo: blankoslo/floq-balance
      branch: develop
  - provider: gcs
    bucket: floq
    local-dir: dist
    upload-dir: balance
    cache_control: "max-age=3600"
    acl: public-read
    access_key_id: GOOGUTBTHMJF3QCW6R7F
    secret_access_key:
      secure: I/9aJ7u/BrImFT7GuBw+1zvj3oG/a8qKhJ14HnIvFsruglZQHl4sT+GzFRmMk+ZV43NW8Nfm4rL/uUt+cEWG4FRKebbNCH4ftueZi9UgDiotHSdOb5DVwBHgmzvGv7lt5mtGpceu7kTxW24hYXxu+q9o+pAaAjVonDMGLSk4P1wORHPEcdAZRlfrNcS55RZNgErDIteB5GbGo2f7ivKnQ0YvayLtupyi73+Ka68BBqnTDu1Y7akkdYq4dp6HD857aXhaZa+Dcsz6JkN2sSAGk0fAJ9VyPQi/pQWFA5D1i1fDillnA1beelXCWrfckPSzrb/nsJoK+srx9jvu7bxLu0NBL/ZwewrTSbr7nE9lmvG6qONxD7U/nBaC2iwSVJIXkQ392Ff2NiQ09htNCxr1w5eqT5s7d/4vlPJ/Yzkm+AWtQJfl2yzaK2k3Ev5gyFt3pa+EgB/wGiJW0u/8n5S0c5rcEROaKluryvOAcRQvmLXfK0FBljl3jf11gW+rO7DG4Dj2YeS67ZYzm+Gcmq3IK6k6gIC4KXuW/oZSGUM+wE7NndfwaYfNcanM1QS/KMuZbW3OTwS/R7wkBhWFWcAURyhKj+4rjvWawzFNn//8Kb0mQjFsnwwt1lBzNbeAH1QIaaFtDa0R4S7nUPHleRW9dkGV5iRsFWvL7Up4m6KIwyo=
    skip_cleanup: true
    on:
      repo: blankoslo/floq-balance
      branch: master
